# Generated by Django 4.2.4 on 2023-10-21 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulsos', models.FloatField(default=None, null=True)),
                ('oxigenacion', models.FloatField(default=None, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
