# Generated by Django 4.2.4 on 2023-10-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BPM', models.JSONField()),
                ('Spo2', models.JSONField()),
                ('Glu', models.JSONField()),
                ('Move', models.JSONField()),
                ('Temp', models.JSONField()),
            ],
        ),
    ]
