# Generated by Django 4.2.4 on 2023-11-14 18:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('healthdatos', '0002_datos_movimiento_datos_temperatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, null=True)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('genero', models.CharField(default=None, null=True)),
                ('contraseña', models.CharField(default=None, null=True)),
            ],
        ),
    ]
