// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl6Ld4mIeJcOE_l4tXWt0HLMyIlkdUPQE',
    appId: '1:98531808956:web:e8ee478e0a2cff934662b9',
    messagingSenderId: '98531808956',
    projectId: 'healthband-910f9',
    authDomain: 'healthband-910f9.firebaseapp.com',
    storageBucket: 'healthband-910f9.appspot.com',
    measurementId: 'G-CK5DJNYKQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoAHyne7OqdQvelda5PsDIL2p5NbfZhiU',
    appId: '1:98531808956:android:c89d29eec2eaadfe4662b9',
    messagingSenderId: '98531808956',
    projectId: 'healthband-910f9',
    storageBucket: 'healthband-910f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjqedA-LS-WhCI1LNpfahGI7cuTgRtWrI',
    appId: '1:98531808956:ios:f6e12daece8dc0e44662b9',
    messagingSenderId: '98531808956',
    projectId: 'healthband-910f9',
    storageBucket: 'healthband-910f9.appspot.com',
    iosBundleId: 'com.example.healthBand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjqedA-LS-WhCI1LNpfahGI7cuTgRtWrI',
    appId: '1:98531808956:ios:2f533077f5fdd9714662b9',
    messagingSenderId: '98531808956',
    projectId: 'healthband-910f9',
    storageBucket: 'healthband-910f9.appspot.com',
    iosBundleId: 'com.example.healthBand.RunnerTests',
  );
}
