// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClEyCpvyHWJh7emzeoaTas9wmL8sJW2QI',
    appId: '1:150511519613:web:c8f3822b050a8839f52e14',
    messagingSenderId: '150511519613',
    projectId: 'hband-3a540',
    authDomain: 'hband-3a540.firebaseapp.com',
    storageBucket: 'hband-3a540.appspot.com',
    measurementId: 'G-PRPVDMGR83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU0D3_7PVDr51Du2sll5dd2YIjFNUkcDA',
    appId: '1:150511519613:android:ae36bebdecb64765f52e14',
    messagingSenderId: '150511519613',
    projectId: 'hband-3a540',
    storageBucket: 'hband-3a540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx8uvwlt1vB1WgYCL2AmzkAf0DvchjwQg',
    appId: '1:150511519613:ios:ee65212723a09234f52e14',
    messagingSenderId: '150511519613',
    projectId: 'hband-3a540',
    storageBucket: 'hband-3a540.appspot.com',
    iosBundleId: 'com.example.healthBand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx8uvwlt1vB1WgYCL2AmzkAf0DvchjwQg',
    appId: '1:150511519613:ios:2455fbc5fa39b2f4f52e14',
    messagingSenderId: '150511519613',
    projectId: 'hband-3a540',
    storageBucket: 'hband-3a540.appspot.com',
    iosBundleId: 'com.example.healthBand.RunnerTests',
  );
}
